title: Nighthawk-Pages
description: "August 2023 to June 2024"
owner_name: Sergi Serpukhovitinov
github_username: sergi1207
github_repo: "usr/sergiStudent"
baseurl: "/sergiStudent"
remote_theme: jekyll/minima
minima:
  social_links:
    - { platform: github, user_url: "https://github.com/nighthawkcoders"}
    - { platform: github, user_url: "https://github.com/Tirth-Thakkar"}
    - { platform: github, user_url: "https://github.com/h4seeb-cmd"}
# remote_theme: pages-themes/dinky@v0.2.0
# remote_theme: pages-themes/minimal@v0.2.0
# remote_theme: pages-themes/hacker@v0.2.0
# remote_theme: pages-themes/cayman@v0.2.0
# remote_theme: pages-themes/time-machine@v0.2.0
plugins:
- jekyll-remote-theme
future: true
